version: "3"
services:
  datamodel-service:
    container_name: datamodel-service
    image: gfpgmbh/pim-datamodel-service:0.0.6
    ports:
      - "${SERVER_PORT}:8088"
    restart: unless-stopped
    environment:
      - _JAVA_OPTIONS="-Xmx8g"
    volumes:
      - ./.env:/env.properties
    networks:
      - postgres-network

networks:
  postgres-network:
    external: true
