version: '3'
services:
  pim-app:
    container_name: pim-service
    image: gfpgmbh/pim:latest
    environment:
      JAVA_OPTIONS: "-Xmx8g -Xms2g -Xss2m"
      TZ: "Europe/Berlin"
    volumes:
      - ./config/pim.cfg:/var/lib/jetty/pim.cfg
      - ./repo:/repo
    ports:
      - "80:8080"
    restart: "unless-stopped"
    networks:
      - mysql-network
      - postgres-network
      - redis-network
      - kafka-network

networks:
  mysql-network:
    external: true
  postgres-network:
    external: true
  redis-network:
    external: true
  kafka-network:
    external: true
volumes:
  config:
  repo:
