version: "3"
services:
  kafka:
    container_name: kafka-service
    image: bitnami/kafka:latest
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    ports:
      - "9094:9094"
    restart: "always"
    networks:
      - kafka-network
    volumes:
      - kafka_data:/bitnami
  kafdrop:
    container_name: kafdrop-service
    image: obsidiandynamics/kafdrop:latest
    environment:
      - SERVER_SERVLET_CONTEXTPATH=/
      - JVM_OPTS=-Xms32M -Xmx64M
      - KAFKA_BROKERCONNECT=kafka:9092
    depends_on:
      - kafka
    ports:
      - "9000:9000"
    restart: "always"
    networks:
      - kafka-network

networks:
  kafka-network:
    external: true

volumes:
  kafka_data:
