version: "3"
services:
  cache:
    container_name: cache-redis
    image: redis:7.2.4-alpine3.19
    command: redis-server --loglevel warning --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    restart: "unless-stopped"
    networks:
      - redis-network
    volumes:
      - cache:/data

networks:
  redis-network:
    external: true

volumes:
  cache:
